# Generated by Django 5.0.6 on 2024-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0002_remove_subcategory_category_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='EMPTY', max_length=20),
        ),
    ]
